server:
  port: 8080
  servlet:
    context-path: /user-management
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/employee_management
    username: root
    password: 687311813
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    enabled: false
